version: '3.4'
networks:
  default:
    external:
      name: learning_network
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports: 
      - 30010:3000